import type { Metadata } from 'next';
import { Geist_Mono, Poppins } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';

import './globals.css';
import 'highlight.js/styles/nnfx-dark.css'; // or any other highlight.js theme
import 'katex/dist/katex.min.css';

import { PostHogProvider } from '@/components/providers/posthog-provider';
import { ThemeProvider } from '@/components/ui/theme';
import QueryProvider from '@/lib/query-provider';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Caret',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  cookies,
}: Readonly<{
  children: React.ReactNode;
  cookies: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${poppins.className} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PostHogProvider>
            <QueryProvider>
              {children}
              {cookies}
            </QueryProvider>
          </PostHogProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
